require 'plissken'
require 'httparty'
require 'virtus'

require 'dotloop/version'
require 'dotloop/authenticate'
require 'dotloop/client'
require 'dotloop/query_param_helpers'
require 'dotloop/parse_data'
require 'dotloop/contact'
require 'dotloop/document'
require 'dotloop/exceptions'
require 'dotloop/folder'
require 'dotloop/loop'
require 'dotloop/loop_detail'
require 'dotloop/participant'
require 'dotloop/profile'
require 'dotloop/task'
require 'dotloop/tasklist'
require 'dotloop/template'

require 'dotloop/models/contact'
require 'dotloop/models/document'
require 'dotloop/models/folder'
require 'dotloop/models/loop'
require 'dotloop/models/participant'
require 'dotloop/models/profile'
require 'dotloop/models/task'
require 'dotloop/models/tasklist'
require 'dotloop/models/template'

require 'dotloop/models/loop_details/contact'
require 'dotloop/models/loop_details/contract_dates'
require 'dotloop/models/loop_details/contract_info'
require 'dotloop/models/loop_details/financials'
require 'dotloop/models/loop_details/geographic_description'
require 'dotloop/models/loop_details/listing_information'
require 'dotloop/models/loop_details/offer_dates'
require 'dotloop/models/loop_details/property_address'
require 'dotloop/models/loop_details/property'
require 'dotloop/models/loop_details/referral'
require 'dotloop/models/loop_detail'

module Dotloop
  # Your code goes here...
end
